import { z } from 'zod';
import { EntityIdSchema, SlugSchema } from '../ids.ts';
import {
  ActionKindSchema,
  AttackFilterSchema,
  DamageTypeSchema,
  DisplaySchema,
  LongTextSchema,
  PreparationSchema,
  ProficiencyLevelSchema,
  ResetSchema,
  RollTargetSchema,
  SenseSchema,
  ShortTextSchema,
  SlotProgressionSchema,
  SpeedModeSchema,
  UsesSchema,
  ValueSchema,
} from './enums.ts';
import { FormulaSchema } from './formula.ts';
import { AbilityKeySchema, ClassRefSchema, PredicateSchema, ProficiencyKindSchema } from './predicate.ts';

export const EFFECT_TYPES = [
  'ability.bonus',
  'ability.set',
  'ability.max',
  'proficiency.grant',
  'ac.formula',
  'ac.bonus',
  'hp.perLevel',
  'hp.bonus',
  'speed.set',
  'speed.bonus',
  'sense.grant',
  'resource.define',
  'spellcasting.define',
  'spell.grant',
  'spell.listAdd',
  'damage.resistance',
  'damage.immunity',
  'damage.vulnerability',
  'condition.immunity',
  'attack.bonus',
  'damage.bonus',
  'damage.rerollBelow',
  'initiative.bonus',
  'save.bonus',
  'skill.bonus',
  'check.bonus',
  'advantage.grant',
  'disadvantage.impose',
  'action.define',
  'feature.text',
  'mastery.grant',
  'extraAttack.set',
  'item.grant',
  'currency.grant',
  'size.set',
  'type.set',
  'language.grant',
  'tag.grant',
  'slot.bonus',
] as const;
export type EffectType = (typeof EFFECT_TYPES)[number];

/** Fields every effect may carry. `key` is the stacking key (defaults to the source feature at derive time). */
const common = {
  when: PredicateSchema.optional(),
  key: z.string().min(1).max(64).optional(),
};

const eff = <T extends EffectType, S extends z.ZodRawShape>(type: T, shape: S) =>
  z.strictObject({ type: z.literal(type), ...common, ...shape });

export const EffectSchema = z.discriminatedUnion('type', [
  eff('ability.bonus', { ability: AbilityKeySchema, value: z.int() }),
  eff('ability.set', { ability: AbilityKeySchema, value: z.int().min(1).max(30), ifHigher: z.boolean().default(true) }),
  eff('ability.max', { ability: AbilityKeySchema, value: z.int().min(20).max(30) }),
  eff('proficiency.grant', {
    kind: ProficiencyKindSchema,
    target: z.string().min(1).max(64),
    level: ProficiencyLevelSchema.default('proficient'),
  }),
  eff('ac.formula', { formula: FormulaSchema }),
  eff('ac.bonus', { value: ValueSchema }),
  eff('hp.perLevel', { value: z.int() }),
  eff('hp.bonus', { value: ValueSchema }),
  eff('speed.set', { mode: SpeedModeSchema, value: z.int().min(0) }),
  eff('speed.bonus', { mode: SpeedModeSchema, value: z.int() }),
  eff('sense.grant', { sense: SenseSchema, range: z.int().min(0) }),
  eff('resource.define', {
    id: SlugSchema,
    name: ShortTextSchema,
    max: FormulaSchema,
    reset: ResetSchema,
    display: DisplaySchema.default('pips'),
  }),
  eff('spellcasting.define', {
    class: ClassRefSchema,
    ability: AbilityKeySchema,
    list: z.union([ClassRefSchema, z.array(EntityIdSchema).min(1)]),
    preparation: PreparationSchema,
    slots: SlotProgressionSchema,
    ritual: z.boolean().default(false),
    focus: z.boolean().default(false),
    cantripsKnown: FormulaSchema.optional(),
    preparedCount: FormulaSchema.optional(),
    spellsKnown: FormulaSchema.optional(),
  }),
  eff('spell.grant', {
    spell: EntityIdSchema,
    castingAbility: AbilityKeySchema.optional(),
    uses: UsesSchema.optional(),
    alwaysPrepared: z.boolean().default(false),
    level: z.int().min(0).max(9).optional(),
  }),
  eff('spell.listAdd', { class: ClassRefSchema, spells: z.array(EntityIdSchema).min(1) }),
  eff('damage.resistance', { types: z.array(DamageTypeSchema).min(1) }),
  eff('damage.immunity', { types: z.array(DamageTypeSchema).min(1) }),
  eff('damage.vulnerability', { types: z.array(DamageTypeSchema).min(1) }),
  eff('condition.immunity', { conditions: z.array(EntityIdSchema).min(1) }),
  eff('attack.bonus', { value: ValueSchema, filter: AttackFilterSchema.optional() }),
  eff('damage.bonus', { value: ValueSchema, filter: AttackFilterSchema.optional() }),
  eff('damage.rerollBelow', { value: z.int().min(1), filter: AttackFilterSchema.optional() }),
  eff('initiative.bonus', { value: ValueSchema }),
  eff('save.bonus', { value: ValueSchema, target: AbilityKeySchema.optional() }),
  eff('skill.bonus', { value: ValueSchema, target: SlugSchema.optional() }),
  eff('check.bonus', { value: ValueSchema, target: AbilityKeySchema.optional() }),
  eff('advantage.grant', { on: RollTargetSchema }),
  eff('disadvantage.impose', { on: RollTargetSchema }),
  eff('action.define', {
    id: SlugSchema,
    name: ShortTextSchema,
    kind: ActionKindSchema,
    description: LongTextSchema,
    uses: UsesSchema.optional(),
    resource: SlugSchema.optional(),
  }),
  eff('feature.text', { name: ShortTextSchema, description: LongTextSchema }),
  eff('mastery.grant', { count: FormulaSchema }),
  eff('extraAttack.set', { count: z.int().min(1).max(4) }),
  eff('item.grant', { item: EntityIdSchema, qty: z.int().min(1).default(1) }),
  eff('currency.grant', {
    cp: z.int().optional(),
    sp: z.int().optional(),
    ep: z.int().optional(),
    gp: z.int().optional(),
    pp: z.int().optional(),
  }),
  eff('size.set', { size: SlugSchema }),
  eff('type.set', { creatureType: SlugSchema }),
  eff('language.grant', { language: EntityIdSchema }),
  eff('tag.grant', { tag: z.string().min(1).max(64) }),
  eff('slot.bonus', { level: z.int().min(1).max(9), count: z.int().min(1) }),
]);
export type Effect = z.infer<typeof EffectSchema>;
