packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true

catalog:
  '@eslint/js': ^10.0.0
  '@types/node': ^24.0.0
  '@types/semver': ^7.7.0
  eslint: ^10.0.0
  prettier: ^3.9.6
  semver: ^7.7.0
  typescript: ~6.0.3
  typescript-eslint: ^8.62.1
  vitest: ^4.1.11
  yaml: ^2.8.0
  zod: ^4.5.4

minimumReleaseAgeExclude:
  - zod@4.5.4
  - '@angular-eslint/builder@22.4.0'
  - '@angular-eslint/bundled-angular-compiler@22.4.0'
  - '@angular-eslint/eslint-plugin-template@22.4.0'
  - '@angular-eslint/eslint-plugin@22.4.0'
  - '@angular-eslint/schematics@22.4.0'
  - '@angular-eslint/template-parser@22.4.0'
  - '@angular-eslint/utils@22.4.0'
  - angular-eslint@22.4.0
