/**
 * `Db` over `drizzle-orm/better-sqlite3` (ADR-014's Node `Db` row): opens `accounts.sqlite` and
 * applies every committed migration (`src/core/db/migrations/`) at startup, mirroring
 * `test/helpers/test-db.ts`'s pattern exactly but against a real file instead of `:memory:` — same
 * driver, same migrator, same schema, just a durable path (doc-10 §Accounts database: "migrations
 * generated by `drizzle-kit` and applied ... at Node startup").
 */
import { fileURLToPath } from 'node:url';
import Database from 'better-sqlite3';
import { drizzle } from 'drizzle-orm/better-sqlite3';
import { migrate } from 'drizzle-orm/better-sqlite3/migrator';
import { schema } from '../../core/db/schema.ts';
import type { Db } from '../../ports/db.ts';

const migrationsFolder = fileURLToPath(new URL('../../core/db/migrations', import.meta.url));

export interface AccountsDbHandle {
  readonly db: Db;
  readonly sqlite: InstanceType<typeof Database>;
  close(): void;
}

/** Opens (creating if absent) `accounts.sqlite` at `path`, applies every migration, and returns
 * the `Db` port value `createApp` expects plus the raw handle for lifecycle management
 * (`close()` — used by tests and graceful shutdown). WAL mode for the same reasons as
 * `store.sqlite-file.ts`'s `openStreamsDb`. */
export function openAccountsDb(path: string): AccountsDbHandle {
  const sqlite = new Database(path);
  sqlite.pragma('journal_mode = WAL');
  sqlite.pragma('foreign_keys = ON');
  const db = drizzle(sqlite, { schema });
  migrate(db, { migrationsFolder });
  return { db, sqlite, close: () => sqlite.close() };
}
